//! The Go client generator.

use surql::schema::{FieldType, TableDefinition};

use crate::emit::{w, wln};
use crate::ir::{ActionOutput, Contract, TypeRef};
use crate::naming::{camel, pascal, singular, snake, type_name};
use crate::openapi::GenerateError;

use super::{
    checked, column, query_kind, query_params, query_takes_id, sub_method_stem, sub_table,
    sub_type_name,
};

pub fn generate_client_go(
    contract: &Contract,
    schema: &[TableDefinition],
) -> Result<String, GenerateError> {
    let resources = checked(contract, schema)?;
    let prefix = contract.prefix();
    let mut out = String::new();
    wln!(
        out,
        "// Code generated by janus for the `{}` contract v{}; DO NOT EDIT.\n",
        contract.name,
        contract.version,
    );
    wln!(out, "package {}\n", snake(&contract.name));
    out.push_str(
        "import (\n\
         \t\"bytes\"\n\
         \t\"encoding/json\"\n\
         \t\"fmt\"\n\
         \t\"net/http\"\n\
         \t\"net/url\"\n\
         )\n\n",
    );

    for (resource, table) in &resources {
        go_struct(
            &mut out,
            &type_name(&resource.name),
            &resource.fields,
            table,
        )?;
        for sub in &resource.sub_resources {
            go_struct(
                &mut out,
                &sub_type_name(resource, sub),
                &sub.fields,
                sub_table(schema, sub)?,
            )?;
        }
    }

    let wire = contract.auth.wire();
    // Go exports struct fields by capitalising them, and takes its
    // constructor parameter in the lower-camel form of the same word.
    // Both derive from one credential, so they are resolved together.
    let go_field = wire.map(|auth| pascal(auth.credential));
    // gofmt aligns a struct's types to one column, so the padding depends
    // on the longest field name -- which the credential can now be. The
    // fallback is the width of "BaseURL", which the array always holds.
    let width = ["BaseURL", "HTTP"]
        .into_iter()
        .chain(go_field.as_deref())
        .map(str::len)
        .max()
        .unwrap_or(const { "BaseURL".len() });
    let pad = |name: &str| " ".repeat(width - name.len() + 1);
    let struct_field = go_field
        .as_ref()
        .map_or_else(String::new, |name| format!("\t{name}{}string\n", pad(name)));
    // Go's shared-type parameter form: `(baseURL, tenant string)`, not
    // `(baseURL string, tenant string)`.
    let ctor_param = wire.map_or_else(
        || "baseURL string".to_owned(),
        |auth| format!("baseURL, {} string", auth.credential),
    );
    let ctor_init = wire.map_or_else(String::new, |auth| {
        format!(", {}: {}", pascal(auth.credential), auth.credential)
    });
    let set_header = wire.map_or_else(String::new, |auth| {
        let (header, name) = (auth.header, pascal(auth.credential));
        if auth.prefix.is_empty() {
            format!("\trequest.Header.Set(\"{header}\", c.{name})\n")
        } else {
            let prefix = auth.prefix;
            format!("\trequest.Header.Set(\"{header}\", \"{prefix}\"+c.{name})\n")
        }
    });
    let base_pad = pad("BaseURL");
    let http_pad = pad("HTTP");
    w!(
        out,
        "type Client struct {{\n\
         \tBaseURL{base_pad}string\n\
         {struct_field}\
         \tHTTP{http_pad}*http.Client\n\
         }}\n\n\
         func NewClient({ctor_param}) *Client {{\n\
         \treturn &Client{{BaseURL: baseURL{ctor_init}, HTTP: http.DefaultClient}}\n\
         }}\n\n",
    );
    // The request helper is fixed text apart from the one header line, and
    // it is dense with Go braces a format macro would try to read as its
    // own. Two plain writes around the spliced line is plainer than
    // escaping every one of them.
    out.push_str(
        "func (c *Client) request(method, path string, body any, out any) error {\n\
         \tvar payload *bytes.Buffer\n\
         \tif body != nil {\n\
         \t\tencoded, err := json.Marshal(body)\n\
         \t\tif err != nil {\n\
         \t\t\treturn err\n\
         \t\t}\n\
         \t\tpayload = bytes.NewBuffer(encoded)\n\
         \t} else {\n\
         \t\tpayload = bytes.NewBuffer(nil)\n\
         \t}\n\
         \trequest, err := http.NewRequest(method, c.BaseURL+path, payload)\n\
         \tif err != nil {\n\
         \t\treturn err\n\
         \t}\n",
    );
    out.push_str(&set_header);
    out.push_str(
        "\tif body != nil {\n\
         \t\trequest.Header.Set(\"content-type\", \"application/json\")\n\
         \t}\n\
         \tresponse, err := c.HTTP.Do(request)\n\
         \tif err != nil {\n\
         \t\treturn err\n\
         \t}\n\
         \tdefer response.Body.Close()\n\
         \tif response.StatusCode >= 400 {\n\
         \t\treturn fmt.Errorf(\"%s %s: %d\", method, path, response.StatusCode)\n\
         \t}\n\
         \tif out == nil || response.StatusCode == 204 {\n\
         \t\treturn nil\n\
         \t}\n\
         \treturn json.NewDecoder(response.Body).Decode(out)\n\
         }\n\n",
    );

    for (resource, _) in &resources {
        let name = type_name(&resource.name);
        if resource.faces.list {
            wln!(
                out,
                "func (c *Client) List{plural}(limit int, cursor string) (*{name}Page, error) {{",
                plural = pascal(&snake(&resource.name)),
            );
            wln!(
                out,
                "\tquery := url.Values{{}}\n\
                 \tif limit > 0 {{\n\
                 \t\tquery.Set(\"limit\", fmt.Sprint(limit))\n\
                 \t}}\n\
                 \tif cursor != \"\" {{\n\
                 \t\tquery.Set(\"cursor\", cursor)\n\
                 \t}}\n\
                 \tpath := \"{prefix}/{plural}\"\n\
                 \tif encoded := query.Encode(); encoded != \"\" {{\n\
                 \t\tpath += \"?\" + encoded\n\
                 \t}}\n\
                 \tvar page {name}Page\n\
                 \tif err := c.request(\"GET\", path, nil, &page); err != nil {{\n\
                 \t\treturn nil, err\n\
                 \t}}\n\
                 \treturn &page, nil\n}}\n",
                plural = resource.name,
            );
        }
        if resource.faces.get {
            wln!(
                out,
                "func (c *Client) Get{single}(id string) (*{name}, error) {{\n\
                 \tvar out {name}\n\
                 \tif err := c.request(\"GET\", \"{prefix}/{plural}/\"+id, nil, &out); err != nil {{\n\
                 \t\treturn nil, err\n\
                 \t}}\n\
                 \treturn &out, nil\n}}\n",
                single = pascal(&singular(&resource.name)),
                plural = resource.name,
            );
        }

        for sub in &resource.sub_resources {
            let sub_name = sub_type_name(resource, sub);
            wln!(
                out,
                "func (c *Client) {stem}(id string, limit int, cursor string) (*{sub_name}Page, error) {{",
                stem = pascal(&sub_method_stem(resource, sub)),
            );
            wln!(
                out,
                "	query := url.Values{{}}
                 	if limit > 0 {{
                 		query.Set(\"limit\", fmt.Sprint(limit))
                 	}}
                 	if cursor != \"\" {{
                 		query.Set(\"cursor\", cursor)
                 	}}
                 	path := \"{prefix}/{parent}/\" + id + \"/{child}\"
                 	if encoded := query.Encode(); encoded != \"\" {{
                 		path += \"?\" + encoded
                 	}}
                 	var page {sub_name}Page
                 	if err := c.request(\"GET\", path, nil, &page); err != nil {{
                 		return nil, err
                 	}}
                 	return &page, nil
}}
",
                parent = resource.name,
                child = sub.name,
            );
        }
        for action in &resource.actions {
            let method_name = format!(
                "{}{}",
                pascal(&snake(&action.name)),
                pascal(&singular(&resource.name)),
            );
            let mut parameters = Vec::new();
            if action.takes_id() {
                parameters.push("id string".to_owned());
            }
            if !action.input.is_empty() {
                parameters.push("input map[string]any".to_owned());
            }
            let path_expression = if action.takes_id() {
                format!(
                    "\"{prefix}/{}\" + {}",
                    resource.name,
                    go_path_expr(&action.path),
                )
            } else {
                format!("\"{prefix}/{}{}\"", resource.name, action.path)
            };
            let body_expression = if action.input.is_empty() {
                "nil"
            } else {
                "input"
            };
            match action.output {
                ActionOutput::Resource => {
                    wln!(
                        out,
                        "func (c *Client) {method_name}({params}) (*{name}, error) {{\n\
                         \tvar out {name}\n\
                         \tif err := c.request(\"{method}\", {path_expression}, {body_expression}, &out); err != nil {{\n\
                         \t\treturn nil, err\n\
                         \t}}\n\
                         \treturn &out, nil\n}}\n",
                        params = parameters.join(", "),
                        method = action.method,
                    );
                }
                ActionOutput::Json => {
                    wln!(
                        out,
                        "func (c *Client) {method_name}({params}) (map[string]any, error) {{\n\
                         \tout := map[string]any{{}}\n\
                         \tif err := c.request(\"{method}\", {path_expression}, {body_expression}, &out); err != nil {{\n\
                         \t\treturn nil, err\n\
                         \t}}\n\
                         \treturn out, nil\n}}\n",
                        params = parameters.join(", "),
                        method = action.method,
                    );
                }
                ActionOutput::None => {
                    wln!(
                        out,
                        "func (c *Client) {method_name}({params}) error {{\n\
                         \treturn c.request(\"{method}\", {path_expression}, {body_expression}, nil)\n}}\n",
                        params = parameters.join(", "),
                        method = action.method,
                    );
                }
            }
        }
    }
    for query in &contract.queries {
        let mut parameters = Vec::new();
        if query_takes_id(query) {
            parameters.push("id string".to_owned());
        }
        for field in query_params(query) {
            parameters.push(format!(
                "{} {}",
                camel(&field.name),
                query_kind(field.kind, "go"),
            ));
        }
        wln!(
            out,
            "func (c *Client) {}({}) (any, error) {{",
            pascal(&snake(&query.name)),
            parameters.join(", "),
        );
        if !query_params(query).is_empty() {
            out.push_str("\tquery := url.Values{}\n");
        }
        for field in query_params(query) {
            let name = &field.name;
            let binding = camel(name);
            // Go has no optional parameter, so an omitted value arrives
            // as the zero value and the zero value is what gets
            // skipped. The generated listings already read this way.
            let guard = match field.kind {
                TypeRef::Int => Some(format!("{binding} > 0")),
                TypeRef::String => Some(format!("{binding} != \"\"")),
                _ => None,
            };
            let setter = match field.kind {
                TypeRef::String => format!("query.Set(\"{name}\", {binding})"),
                _ => format!("query.Set(\"{name}\", fmt.Sprint({binding}))"),
            };
            match (field.required, guard) {
                (false, Some(condition)) => {
                    wln!(out, "\tif {condition} {{\n\t\t{setter}\n\t}}");
                }
                _ => wln!(out, "\t{setter}"),
            }
        }
        let path_expression = if query_takes_id(query) {
            go_path_expr(&query.path)
        } else {
            format!("\"{}\"", query.path)
        };
        wln!(out, "\tpath := {path_expression}");
        if !query_params(query).is_empty() {
            out.push_str(
                "\tif encoded := query.Encode(); encoded != \"\" {\n\
                 \t\tpath += \"?\" + encoded\n\t}\n",
            );
        }
        out.push_str(
            "\tvar out any\n\
             \tif err := c.request(\"GET\", path, nil, &out); err != nil {\n\
             \t\treturn nil, err\n\t}\n\
             \treturn out, nil\n}\n\n",
        );
    }
    Ok(out)
}

fn go_path_expr(path: &str) -> String {
    // Only reached for a path that takes an id, but a path without one
    // has an obvious answer -- itself, quoted -- so there is nothing to
    // gain by insisting the caller was right.
    let Some((before, after)) = path.split_once("{id}") else {
        return format!("\"{path}\"");
    };
    let mut expression = String::new();
    if !before.is_empty() {
        expression.push_str(&format!("\"{before}\" + "));
    }
    expression.push_str("id");
    if !after.is_empty() {
        expression.push_str(&format!(" + \"{after}\""));
    }
    expression
}

fn go_struct(
    out: &mut String,
    name: &str,
    fields: &[crate::ir::FieldExposure],
    table: &TableDefinition,
) -> Result<(), GenerateError> {
    wln!(out, "type {name} struct {{");
    wln!(out, "\tID string `json:\"id\"`");
    for exposure in fields {
        let field = column(table, &exposure.column)?;
        let base = match field.field_type {
            FieldType::Int => "int64",
            FieldType::Float | FieldType::Decimal | FieldType::Number => "float64",
            FieldType::Bool => "bool",
            FieldType::Object | FieldType::Array | FieldType::Geometry | FieldType::Any => "any",
            _ => "string",
        };
        let go_type = if (field.nullable || exposure.guard.is_some()) && base != "any" {
            format!("*{base}")
        } else {
            base.to_owned()
        };
        let api = exposure.api_name();
        wln!(out, "\t{} {go_type} `json:\"{api}\"`", pascal(&snake(api)));
    }
    wln!(out, "}}\n");
    wln!(out, "type {name}Page struct {{");
    wln!(out, "\tItems []{name} `json:\"items\"`");
    wln!(out, "\tNextCursor *string `json:\"next_cursor\"`");
    wln!(out, "}}\n");
    Ok(())
}
