//! The Python client generator.

use std::fmt::Write as _;

use surql::schema::{FieldType, TableDefinition};

use crate::ir::{ActionOutput, Contract};
use crate::naming::{singular, snake, type_name};
use crate::openapi::GenerateError;

use super::{
    checked, column, query_kind, query_params, query_takes_id, sub_method_stem, sub_table,
    sub_type_name,
};

pub fn generate_client_py(
    contract: &Contract,
    schema: &[TableDefinition],
) -> Result<String, GenerateError> {
    let resources = checked(contract, schema)?;
    let mut out = String::new();
    writeln!(
        out,
        "\"\"\"Generated by janus for the `{}` contract v{}. Do not edit.\"\"\"\n",
        contract.name, contract.version,
    )
    .unwrap();
    out.push_str(
        "from __future__ import annotations\n\n\
         import json\n\
         import urllib.parse\n\
         import urllib.request\n\
         from dataclasses import dataclass, field\n\
         from typing import Any\n\n",
    );

    for (resource, table) in &resources {
        py_dataclass(
            &mut out,
            &type_name(&resource.name),
            &resource.fields,
            table,
        );
        for sub in &resource.sub_resources {
            py_dataclass(
                &mut out,
                &sub_type_name(resource, sub),
                &sub.fields,
                sub_table(schema, sub),
            );
        }
    }

    out.push_str(
        "class Client:\n\
         \x20 def __init__(self, base_url: str, tenant: str) -> None:\n\
         \x20   self.base_url = base_url.rstrip('/')\n\
         \x20   self.tenant = tenant\n\n\
         \x20 def _request(self, method: str, path: str, body: dict[str, Any] | None = None) -> Any:\n\
         \x20   data = None if body is None else json.dumps(body).encode()\n\
         \x20   headers = {'x-copal-tenant': self.tenant}\n\
         \x20   if data is not None:\n\
         \x20     headers['content-type'] = 'application/json'\n\
         \x20   request = urllib.request.Request(\n\
         \x20     f'{self.base_url}{path}', data=data, headers=headers, method=method,\n\
         \x20   )\n\
         \x20   with urllib.request.urlopen(request) as response:\n\
         \x20     if response.status == 204:\n\
         \x20       return None\n\
         \x20     return json.loads(response.read())\n\n",
    );

    for (resource, _) in &resources {
        let name = type_name(&resource.name);
        let fields_from = format!(
            "{name}(**{{k: v for k, v in item.items() if k in {name}.__dataclass_fields__}})"
        );
        writeln!(
            out,
            "  def list_{plural}(self, limit: int | None = None, cursor: str | None = None) -> {name}Page:",
            plural = snake(&resource.name),
        )
        .unwrap();
        writeln!(
            out,
            "    query = {{k: v for k, v in {{'limit': limit, 'cursor': cursor}}.items() if v is not None}}\n\
             \x20   suffix = f'?{{urllib.parse.urlencode(query)}}' if query else ''\n\
             \x20   payload = self._request('GET', f'/v1/{plural}{{suffix}}')\n\
             \x20   return {name}Page(\n\
             \x20     items=[{fields_from} for item in payload.get('items', [])],\n\
             \x20     next_cursor=payload.get('next_cursor'),\n\
             \x20   )\n",
            plural = resource.name,
        )
        .unwrap();
        writeln!(
            out,
            "  def get_{single}(self, id: str) -> {name}:\n\
             \x20   item = self._request('GET', f'/v1/{plural}/{{id}}')\n\
             \x20   return {fields_from}\n",
            single = snake(&singular(&resource.name)),
            plural = resource.name,
        )
        .unwrap();

        for sub in &resource.sub_resources {
            let sub_name = sub_type_name(resource, sub);
            let sub_from = format!(
                "{sub_name}(**{{k: v for k, v in item.items() if k in {sub_name}.__dataclass_fields__}})"
            );
            writeln!(
                out,
                "  def {stem}(self, id: str, limit: int | None = None, cursor: str | None = None) -> {sub_name}Page:",
                stem = snake(&sub_method_stem(resource, sub)),
            )
            .unwrap();
            let body = [
                "    query = {k: v for k, v in {'limit': limit, 'cursor': cursor}.items() if v is not None}"
                    .to_owned(),
                "    suffix = f'?{urllib.parse.urlencode(query)}' if query else ''".to_owned(),
                format!(
                    "    payload = self._request('GET', f'/v1/{parent}/{{id}}/{child}{{suffix}}')",
                    parent = resource.name,
                    child = sub.name,
                ),
                format!("    return {sub_name}Page("),
                format!("      items=[{sub_from} for item in payload.get('items', [])],"),
                "      next_cursor=payload.get('next_cursor'),".to_owned(),
                "    )".to_owned(),
            ];
            writeln!(out, "{}", body.join("\n")).unwrap();
        }
        for action in &resource.actions {
            let method_fn = format!(
                "{}_{}",
                snake(&action.name),
                snake(&singular(&resource.name)),
            );
            let mut parameters = vec!["self".to_owned()];
            if action.takes_id() {
                parameters.push("id: str".to_owned());
            }
            if !action.input.is_empty() {
                parameters.push("body: dict[str, Any] | None = None".to_owned());
            }
            let returns = match action.output {
                ActionOutput::Resource => name.clone(),
                ActionOutput::Json => "Any".to_owned(),
                ActionOutput::None => "None".to_owned(),
            };
            // The literal `{id}` survives into the generated f-string,
            // where the method's `id` parameter interpolates.
            let path = &action.path;
            let body_argument = if action.input.is_empty() {
                String::new()
            } else {
                ", body or {}".to_owned()
            };
            writeln!(
                out,
                "  def {method_fn}({params}) -> {returns}:",
                params = parameters.join(", "),
            )
            .unwrap();
            match action.output {
                ActionOutput::Resource => {
                    writeln!(
                        out,
                        "    item = self._request('{method}', f'/v1/{plural}{path}'{body_argument})\n\
                         \x20   return {fields_from}\n",
                        method = action.method,
                        plural = resource.name,
                    )
                    .unwrap();
                }
                _ => {
                    writeln!(
                        out,
                        "    return self._request('{method}', f'/v1/{plural}{path}'{body_argument})\n",
                        method = action.method,
                        plural = resource.name,
                    )
                    .unwrap();
                }
            }
        }
    }
    for query in &contract.queries {
        let mut parameters = vec!["self".to_owned()];
        if query_takes_id(query) {
            parameters.push("id: str".to_owned());
        }
        for field in query_params(query) {
            let kind = query_kind(field.kind, "py");
            parameters.push(if field.required {
                format!("{}: {kind}", snake(&field.name))
            } else {
                format!("{}: {kind} | None = None", snake(&field.name))
            });
        }
        writeln!(
            out,
            "  def {}({}) -> Any:",
            snake(&query.name),
            parameters.join(", "),
        )
        .unwrap();
        if query_params(query).is_empty() {
            writeln!(out, "    return self._request('GET', f'{}')\n", query.path).unwrap();
        } else {
            let pairs: Vec<String> = query_params(query)
                .iter()
                .map(|field| format!("'{}': {}", field.name, snake(&field.name)))
                .collect();
            writeln!(
                out,
                "    query = {{k: v for k, v in {{{}}}.items() if v is not None}}",
                pairs.join(", "),
            )
            .unwrap();
            out.push_str("    suffix = f'?{urllib.parse.urlencode(query)}' if query else ''\n");
            writeln!(
                out,
                "    return self._request('GET', f'{}{{suffix}}')\n",
                query.path,
            )
            .unwrap();
        }
    }
    Ok(out)
}

/// One Python dataclass plus its page envelope. Required attributes
fn py_dataclass(
    out: &mut String,
    name: &str,
    fields: &[crate::ir::FieldExposure],
    table: &TableDefinition,
) {
    writeln!(out, "@dataclass\nclass {name}:").unwrap();
    writeln!(out, "  id: str").unwrap();
    let mut required_lines = Vec::new();
    let mut optional_lines = Vec::new();
    for exposure in fields {
        let schema_field = column(table, &exposure.column);
        let base = match schema_field.field_type {
            FieldType::Int => "int",
            FieldType::Float | FieldType::Decimal | FieldType::Number => "float",
            FieldType::Bool => "bool",
            FieldType::Object | FieldType::Array | FieldType::Geometry | FieldType::Any => "Any",
            _ => "str",
        };
        let attribute = snake(exposure.api_name());
        if schema_field.nullable || exposure.guard.is_some() {
            optional_lines.push(format!("  {attribute}: {base} | None = None"));
        } else {
            required_lines.push(format!("  {attribute}: {base}"));
        }
    }
    for line in required_lines.into_iter().chain(optional_lines) {
        writeln!(out, "{line}").unwrap();
    }
    writeln!(out).unwrap();
    writeln!(out, "@dataclass\nclass {name}Page:").unwrap();
    writeln!(out, "  items: list[{name}] = field(default_factory=list)").unwrap();
    writeln!(out, "  next_cursor: str | None = None\n").unwrap();
}
