//! The Rust client generator.

use std::fmt::Write as _;

use surql::schema::{FieldType, TableDefinition};

use crate::ir::{ActionOutput, Contract};
use crate::naming::{singular, snake, type_name};
use crate::openapi::GenerateError;

use super::{
    checked, column, query_kind, query_params, query_takes_id, sub_method_stem, sub_table,
    sub_type_name,
};

/// Generate the Rust client (reqwest + serde).
pub fn generate_client_rs(
    contract: &Contract,
    schema: &[TableDefinition],
) -> Result<String, GenerateError> {
    let resources = checked(contract, schema)?;
    let mut out = String::new();
    writeln!(
        out,
        "//! Generated by janus for the `{}` contract v{}. Do not edit.\n\
         //!\n\
         //! Dependencies: reqwest = {{ features = [\"json\"] }}, serde =\n\
         //! {{ features = [\"derive\"] }}, serde_json.\n",
        contract.name, contract.version,
    )
    .unwrap();
    out.push_str("use serde::Deserialize;\nuse serde_json::Value;\n\n");

    for (resource, table) in &resources {
        rust_struct(
            &mut out,
            &type_name(&resource.name),
            &resource.fields,
            table,
        );
        for sub in &resource.sub_resources {
            rust_struct(
                &mut out,
                &sub_type_name(resource, sub),
                &sub.fields,
                sub_table(schema, sub),
            );
        }
    }

    out.push_str(
        "#[derive(Debug, Clone)]\n\
         pub struct Client {\n\
         \x20   base_url: String,\n\
         \x20   tenant: String,\n\
         \x20   http: reqwest::Client,\n\
         }\n\n\
         pub type Error = Box<dyn std::error::Error + Send + Sync>;\n\n\
         impl Client {\n\
         \x20   pub fn new(base_url: impl Into<String>, tenant: impl Into<String>) -> Self {\n\
         \x20       Self {\n\
         \x20           base_url: base_url.into(),\n\
         \x20           tenant: tenant.into(),\n\
         \x20           http: reqwest::Client::new(),\n\
         \x20       }\n\
         \x20   }\n\n",
    );

    for (resource, _) in &resources {
        let name = type_name(&resource.name);
        let list_fn = format!("list_{}", snake(&resource.name));
        let get_fn = format!("get_{}", snake(&singular(&resource.name)));
        writeln!(
            out,
            "    pub async fn {list_fn}(&self, limit: Option<u32>, cursor: Option<&str>) \
             -> Result<{name}Page, Error> {{"
        )
        .unwrap();
        writeln!(
            out,
            "        let mut url = format!(\"{{}}/v1/{}\", self.base_url);",
            resource.name,
        )
        .unwrap();
        out.push_str(
            "        let mut query: Vec<(String, String)> = Vec::new();\n\
             \x20       if let Some(limit) = limit { query.push((\"limit\".into(), limit.to_string())); }\n\
             \x20       if let Some(cursor) = cursor { query.push((\"cursor\".into(), cursor.to_string())); }\n\
             \x20       if !query.is_empty() {\n\
             \x20           let joined: Vec<String> = query.iter().map(|(k, v)| format!(\"{k}={v}\")).collect();\n\
             \x20           url = format!(\"{url}?{}\", joined.join(\"&\"));\n\
             \x20       }\n",
        );
        writeln!(
            out,
            "        Ok(self.http.get(url).header(\"x-copal-tenant\", &self.tenant)\
             .send().await?.error_for_status()?.json().await?)"
        )
        .unwrap();
        out.push_str("    }\n\n");
        writeln!(
            out,
            "    pub async fn {get_fn}(&self, id: &str) -> Result<{name}, Error> {{"
        )
        .unwrap();
        writeln!(
            out,
            "        let url = format!(\"{{}}/v1/{}/{{id}}\", self.base_url);",
            resource.name,
        )
        .unwrap();
        writeln!(
            out,
            "        Ok(self.http.get(url).header(\"x-copal-tenant\", &self.tenant)\
             .send().await?.error_for_status()?.json().await?)"
        )
        .unwrap();
        out.push_str("    }\n\n");

        // One list method per sub-collection, reached through the
        // parent id.
        for sub in &resource.sub_resources {
            let sub_name = sub_type_name(resource, sub);
            writeln!(
                out,
                "    pub async fn {stem}(&self, id: &str, limit: Option<u32>, cursor: Option<&str>)                  -> Result<{sub_name}Page, Error> {{",
                stem = sub_method_stem(resource, sub),
            )
            .unwrap();
            writeln!(
                out,
                "        let mut url = format!(\"{{}}/v1/{}/{{id}}/{}\", self.base_url);",
                resource.name, sub.name,
            )
            .unwrap();
            out.push_str(
                "        let mut query: Vec<(String, String)> = Vec::new();
                         if let Some(limit) = limit { query.push((\"limit\".into(), limit.to_string())); }
                         if let Some(cursor) = cursor { query.push((\"cursor\".into(), cursor.to_string())); }
                         if !query.is_empty() {
                             let joined: Vec<String> = query.iter().map(|(k, v)| format!(\"{k}={v}\")).collect();
                             url = format!(\"{url}?{}\", joined.join(\"&\"));
                         }
                         Ok(self.http.get(url).header(\"x-copal-tenant\", &self.tenant)                 .send().await?.error_for_status()?.json().await?)
    }

",
            );
        }
        for action in &resource.actions {
            let method_fn = format!(
                "{}_{}",
                snake(&action.name),
                snake(&singular(&resource.name))
            );
            let mut parameters = vec!["&self".to_owned()];
            if action.takes_id() {
                parameters.push("id: &str".to_owned());
            }
            if !action.input.is_empty() {
                parameters.push("input: Value".to_owned());
            }
            let output = match action.output {
                ActionOutput::Resource => name.clone(),
                ActionOutput::Json => "Value".to_owned(),
                ActionOutput::None => "()".to_owned(),
            };
            writeln!(
                out,
                "    pub async fn {method_fn}({}) -> Result<{output}, Error> {{",
                parameters.join(", "),
            )
            .unwrap();
            // The literal `{id}` survives into the generated format!
            // string, where the method's `id` parameter interpolates.
            writeln!(
                out,
                "        let url = format!(\"{{}}/v1/{}{}\", self.base_url);",
                resource.name, action.path,
            )
            .unwrap();
            let verb = action.method.to_ascii_lowercase();
            let mut call =
                format!("self.http.{verb}(url).header(\"x-copal-tenant\", &self.tenant)");
            if !action.input.is_empty() {
                call.push_str(".json(&input)");
            }
            match action.output {
                ActionOutput::None => {
                    writeln!(
                        out,
                        "        {call}.send().await?.error_for_status()?;\n        Ok(())"
                    )
                    .unwrap();
                }
                _ => {
                    writeln!(
                        out,
                        "        Ok({call}.send().await?.error_for_status()?.json().await?)"
                    )
                    .unwrap();
                }
            }
            out.push_str("    }\n\n");
        }
    }
    // Queries: declared reads that are not listings. They reach REST
    // as GETs with their inputs in the query string, which is why they
    // carry no body and return open JSON.
    for query in &contract.queries {
        let mut parameters = vec!["&self".to_owned()];
        if query_takes_id(query) {
            parameters.push("id: &str".to_owned());
        }
        for field in query_params(query) {
            let kind = query_kind(field.kind, "rs");
            parameters.push(if field.required {
                format!("{}: {kind}", snake(&field.name))
            } else {
                format!("{}: Option<{kind}>", snake(&field.name))
            });
        }
        writeln!(
            out,
            "    pub async fn {}({}) -> Result<Value, Error> {{",
            snake(&query.name),
            parameters.join(", "),
        )
        .unwrap();
        writeln!(
            out,
            "        let url = format!(\"{{}}{}\", self.base_url);",
            query.path,
        )
        .unwrap();
        // `mut` only when something reassigns it, so a query with no
        // parameters does not generate a warning in the client.
        let binding = if query_params(query).is_empty() {
            "let request"
        } else {
            "let mut request"
        };
        writeln!(
            out,
            "        {binding} = self.http.get(url)\n\
             \x20           .header(\"x-copal-tenant\", &self.tenant);",
        )
        .unwrap();
        for field in query_params(query) {
            let name = &field.name;
            let binding = snake(name);
            if field.required {
                writeln!(
                    out,
                    "        request = request.query(&[(\"{name}\", {binding})]);",
                )
                .unwrap();
            } else {
                writeln!(
                    out,
                    "        if let Some(value) = {binding} {{\n\
                     \x20           request = request.query(&[(\"{name}\", value)]);\n\
                     \x20       }}",
                )
                .unwrap();
            }
        }
        out.push_str(
            "        Ok(request.send().await?.error_for_status()?.json().await?)\n    }\n\n",
        );
    }
    out.push_str("}\n");
    Ok(out)
}

fn rust_struct(
    out: &mut String,
    name: &str,
    fields: &[crate::ir::FieldExposure],
    table: &TableDefinition,
) {
    writeln!(out, "#[derive(Debug, Clone, Deserialize)]").unwrap();
    writeln!(out, "pub struct {name} {{").unwrap();
    writeln!(out, "    pub id: String,").unwrap();
    for exposure in fields {
        let field = column(table, &exposure.column);
        let base = match field.field_type {
            FieldType::Int => "i64",
            FieldType::Float | FieldType::Decimal | FieldType::Number => "f64",
            FieldType::Bool => "bool",
            FieldType::Object | FieldType::Array | FieldType::Geometry | FieldType::Any => "Value",
            _ => "String",
        };
        let optional = field.nullable || exposure.guard.is_some();
        let ty = if optional {
            format!("Option<{base}>")
        } else {
            base.to_owned()
        };
        let api = exposure.api_name();
        if optional {
            writeln!(out, "    #[serde(default)]").unwrap();
        }
        writeln!(out, "    pub {}: {ty},", snake(api)).unwrap();
    }
    writeln!(out, "}}\n").unwrap();
    writeln!(out, "#[derive(Debug, Clone, Deserialize)]").unwrap();
    writeln!(out, "pub struct {name}Page {{").unwrap();
    writeln!(out, "    pub items: Vec<{name}>,").unwrap();
    writeln!(out, "    #[serde(default)]").unwrap();
    writeln!(out, "    pub next_cursor: Option<String>,").unwrap();
    writeln!(out, "}}\n").unwrap();
}
