//! The TypeScript client generator.

use surql::schema::{FieldType, TableDefinition};

use crate::emit::wln;
use crate::ir::{ActionOutput, Contract};
use crate::naming::{camel, singular, snake, type_name};
use crate::openapi::GenerateError;

use super::{
    checked, column, query_kind, query_params, query_takes_id, sub_method_stem, sub_table,
    sub_type_name,
};

pub fn generate_client_ts(
    contract: &Contract,
    schema: &[TableDefinition],
) -> Result<String, GenerateError> {
    let resources = checked(contract, schema)?;
    let prefix = contract.prefix();
    let mut out = String::new();
    wln!(
        out,
        "// Generated by janus for the `{}` contract v{}. Do not edit.\n",
        contract.name,
        contract.version,
    );

    for (resource, table) in &resources {
        ts_interface(
            &mut out,
            &type_name(&resource.name),
            &resource.fields,
            table,
        )?;
        for sub in &resource.sub_resources {
            ts_interface(
                &mut out,
                &sub_type_name(resource, sub),
                &sub.fields,
                sub_table(schema, sub)?,
            )?;
        }
    }

    // The credential the contract declared, in the one place every
    // request funnels through.
    let wire = contract.auth.wire();
    let param = wire.map_or_else(String::new, |a| {
        format!(", private {}: string", a.credential)
    });
    let header = wire.map_or_else(String::new, |auth| {
        let (name, value) = (auth.header, auth.credential);
        // A template literal only where there is a prefix to join;
        // `\u{60}${this.tenant}\u{60}` for a bare value is noise.
        if auth.prefix.is_empty() {
            format!("        '{name}': this.{value},\n")
        } else {
            let prefix = auth.prefix;
            format!("        '{name}': `{prefix}${{this.{value}}}`,\n")
        }
    });
    wln!(
        out,
        "export class Client {{\n\
         \x20 constructor(private baseUrl: string{param}) {{}}\n\n\
         \x20 private async request<T>(method: string, path: string, body?: unknown): Promise<T> {{\n\
         \x20   const response = await fetch(`${{this.baseUrl}}${{path}}`, {{\n\
         \x20     method,\n\
         \x20     headers: {{\n\
         {header}\
         \x20       ...(body === undefined ? {{}} : {{ 'content-type': 'application/json' }}),\n\
         \x20     }},\n\
         \x20     body: body === undefined ? undefined : JSON.stringify(body),\n\
         \x20   }})\n\
         \x20   if (!response.ok) throw new Error(`${{method}} ${{path}}: ${{response.status}}`)\n\
         \x20   if (response.status === 204) return undefined as T\n\
         \x20   return (await response.json()) as T\n\
         \x20 }}\n",
    );

    for (resource, _) in &resources {
        let name = type_name(&resource.name);
        let list_fn = camel(&format!("list_{}", snake(&resource.name)));
        let get_fn = camel(&format!("get_{}", snake(&singular(&resource.name))));
        if resource.faces.list {
            wln!(
                out,
                "  {list_fn}(limit?: number, cursor?: string): Promise<{name}Page> {{"
            );
            wln!(
                out,
                "    const query = new URLSearchParams()\n\
                 \x20   if (limit !== undefined) query.set('limit', String(limit))\n\
                 \x20   if (cursor !== undefined) query.set('cursor', cursor)\n\
                 \x20   const suffix = query.size > 0 ? `?${{query}}` : ''\n\
                 \x20   return this.request('GET', `{prefix}/{}${{suffix}}`)",
                resource.name,
            );
            out.push_str("  }\n\n");
        }
        if resource.faces.get {
            wln!(out, "  {get_fn}(id: string): Promise<{name}> {{");
            wln!(
                out,
                "    return this.request('GET', `{prefix}/{}/${{id}}`)",
                resource.name,
            );
            out.push_str("  }\n\n");
        }

        for sub in &resource.sub_resources {
            let sub_name = sub_type_name(resource, sub);
            wln!(
                out,
                "  {stem}(id: string, limit?: number, cursor?: string): Promise<{sub_name}Page> {{",
                stem = camel(&sub_method_stem(resource, sub)),
            );
            wln!(
                out,
                "    const query = new URLSearchParams()
                     if (limit !== undefined) query.set('limit', String(limit))
                     if (cursor !== undefined) query.set('cursor', cursor)
                     const suffix = query.size > 0 ? `?${{query}}` : ''
                     return this.request('GET', `{prefix}/{}/${{id}}/{}${{suffix}}`)",
                resource.name,
                sub.name,
            );
            out.push_str(
                "  }

",
            );
        }
        for action in &resource.actions {
            let method_fn = camel(&format!(
                "{}_{}",
                snake(&action.name),
                snake(&singular(&resource.name)),
            ));
            let mut parameters = Vec::new();
            if action.takes_id() {
                parameters.push("id: string".to_owned());
            }
            if !action.input.is_empty() {
                parameters.push("input: Record<string, unknown>".to_owned());
            }
            let output = match action.output {
                ActionOutput::Resource => name.clone(),
                ActionOutput::Json => "Record<string, unknown>".to_owned(),
                ActionOutput::None => "void".to_owned(),
            };
            let path = action.path.replace("{id}", "${id}");
            let body_argument = if action.input.is_empty() {
                ""
            } else {
                ", input"
            };
            wln!(
                out,
                "  {method_fn}({}): Promise<{output}> {{",
                parameters.join(", "),
            );
            wln!(
                out,
                "    return this.request('{}', `{prefix}/{}{path}`{body_argument})",
                action.method,
                resource.name,
            );
            out.push_str("  }\n\n");
        }
    }
    // Queries reach REST as GETs carrying their inputs in the query
    // string. They declare no output shape, so the method answers with
    // open JSON.
    for query in &contract.queries {
        let mut parameters = Vec::new();
        if query_takes_id(query) {
            parameters.push("id: string".to_owned());
        }
        for field in query_params(query) {
            let kind = query_kind(field.kind, "ts");
            parameters.push(if field.required {
                format!("{}: {kind}", camel(&field.name))
            } else {
                format!("{}?: {kind}", camel(&field.name))
            });
        }
        wln!(
            out,
            "  {}({}): Promise<unknown> {{",
            camel(&query.name),
            parameters.join(", "),
        );
        let path = query.path.replace("{id}", "${id}");
        if query_params(query).is_empty() {
            // Nothing to encode, so nothing is built.
            wln!(out, "    return this.request('GET', `{path}`)");
        } else {
            out.push_str("    const query = new URLSearchParams()\n");
            for field in query_params(query) {
                let name = &field.name;
                let binding = camel(name);
                if field.required {
                    wln!(out, "    query.set('{name}', String({binding}))");
                } else {
                    wln!(
                        out,
                        "    if ({binding} !== undefined) query.set('{name}', String({binding}))",
                    );
                }
            }
            out.push_str("    const suffix = query.size > 0 ? `?${query}` : ''\n");
            wln!(out, "    return this.request('GET', `{path}${{suffix}}`)");
        }
        out.push_str("  }\n\n");
    }
    out.push_str("}\n");
    Ok(out)
}

fn ts_interface(
    out: &mut String,
    name: &str,
    fields: &[crate::ir::FieldExposure],
    table: &TableDefinition,
) -> Result<(), GenerateError> {
    wln!(out, "export interface {name} {{");
    wln!(out, "  id: string");
    for exposure in fields {
        let field = column(table, &exposure.column)?;
        let base = match field.field_type {
            FieldType::Int | FieldType::Float | FieldType::Decimal | FieldType::Number => "number",
            FieldType::Bool => "boolean",
            FieldType::Object | FieldType::Array | FieldType::Geometry | FieldType::Any => {
                "unknown"
            }
            _ => "string",
        };
        let optional = if field.nullable || exposure.guard.is_some() {
            "?"
        } else {
            ""
        };
        wln!(out, "  {}{optional}: {base}", camel(exposure.api_name()));
    }
    wln!(out, "}}\n");
    wln!(out, "export interface {name}Page {{");
    wln!(out, "  items: {name}[]");
    wln!(out, "  next_cursor?: string | null");
    wln!(out, "}}\n");
    Ok(())
}
