//! Generated by kayak for the `copal` contract v0.1.0. Do not edit.
//!
//! Dependencies: reqwest = { features = ["json", "blocking"] }, serde =
//! { features = ["derive"] }, serde_json.

use serde::Deserialize;
use serde_json::Value;

#[derive(Debug, Clone, Deserialize)]
pub struct File {
    pub id: String,
    pub path: String,
    pub state: String,
    pub content_type: String,
    #[serde(default)]
    pub size: Option<i64>,
    #[serde(default)]
    pub digest: Option<String>,
    pub metadata: Value,
    pub created_at: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct FilePage {
    pub items: Vec<File>,
    #[serde(default)]
    pub next_cursor: Option<String>,
}

#[derive(Debug, Clone)]
pub struct Client {
    base_url: String,
    tenant: String,
    http: reqwest::blocking::Client,
}

pub type Error = Box<dyn std::error::Error + Send + Sync>;

impl Client {
    pub fn new(base_url: impl Into<String>, tenant: impl Into<String>) -> Self {
        Self {
            base_url: base_url.into(),
            tenant: tenant.into(),
            http: reqwest::blocking::Client::new(),
        }
    }

    pub fn list_files(&self, limit: Option<u32>, cursor: Option<&str>) -> Result<FilePage, Error> {
        let url = format!("{}/v1/files", self.base_url);
        let mut query: Vec<(&str, String)> = Vec::new();
        if let Some(limit) = limit { query.push(("limit", limit.to_string())); }
        if let Some(cursor) = cursor { query.push(("cursor", cursor.to_string())); }
        Ok(self.http.get(url).header("x-copal-tenant", &self.tenant).query(&query).send()?.error_for_status()?.json()?)
    }

    pub fn get_file(&self, id: &str) -> Result<File, Error> {
        let url = format!("{}/v1/files/{id}", self.base_url);
        Ok(self.http.get(url).header("x-copal-tenant", &self.tenant).send()?.error_for_status()?.json()?)
    }

    pub fn issue_url_file(&self, id: &str, input: Value) -> Result<Value, Error> {
        let url = format!("{}/v1/files/{id}/url", self.base_url);
        Ok(self.http.post(url).header("x-copal-tenant", &self.tenant).json(&input).send()?.error_for_status()?.json()?)
    }

    pub fn remove_file(&self, id: &str) -> Result<(), Error> {
        let url = format!("{}/v1/files/{id}", self.base_url);
        self.http.delete(url).header("x-copal-tenant", &self.tenant).send()?.error_for_status()?;
        Ok(())
    }

    pub fn search(&self, q: &str, limit: Option<i64>) -> Result<Value, Error> {
        let url = format!("{}/v1/search", self.base_url);
        let mut request = self.http.get(url)
            .header("x-copal-tenant", &self.tenant);
        request = request.query(&[("q", q)]);
        if let Some(value) = limit {
            request = request.query(&[("limit", value)]);
        }
        Ok(request.send()?.error_for_status()?.json()?)
    }

    pub fn file_text(&self, id: &str) -> Result<Value, Error> {
        let url = format!("{}/v1/files/{id}/text", self.base_url);
        let request = self.http.get(url)
            .header("x-copal-tenant", &self.tenant);
        Ok(request.send()?.error_for_status()?.json()?)
    }

}
