// Code generated by janus for the `copal` contract v0.1.0; DO NOT EDIT.

package copal

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
)

type File struct {
	ID string `json:"id"`
	Path string `json:"path"`
	State string `json:"state"`
	ContentType string `json:"content_type"`
	Size *int64 `json:"size"`
	Digest *string `json:"digest"`
	Metadata any `json:"metadata"`
	CreatedAt string `json:"created_at"`
}

type FilePage struct {
	Items []File `json:"items"`
	NextCursor *string `json:"next_cursor"`
}

type Client struct {
	BaseURL string
	Tenant  string
	HTTP    *http.Client
}

func NewClient(baseURL, tenant string) *Client {
	return &Client{BaseURL: baseURL, Tenant: tenant, HTTP: http.DefaultClient}
}

func (c *Client) request(method, path string, body any, out any) error {
	var payload *bytes.Buffer
	if body != nil {
		encoded, err := json.Marshal(body)
		if err != nil {
			return err
		}
		payload = bytes.NewBuffer(encoded)
	} else {
		payload = bytes.NewBuffer(nil)
	}
	request, err := http.NewRequest(method, c.BaseURL+path, payload)
	if err != nil {
		return err
	}
	request.Header.Set("x-copal-tenant", c.Tenant)
	if body != nil {
		request.Header.Set("content-type", "application/json")
	}
	response, err := c.HTTP.Do(request)
	if err != nil {
		return err
	}
	defer response.Body.Close()
	if response.StatusCode >= 400 {
		return fmt.Errorf("%s %s: %d", method, path, response.StatusCode)
	}
	if out == nil || response.StatusCode == 204 {
		return nil
	}
	return json.NewDecoder(response.Body).Decode(out)
}

func (c *Client) ListFiles(limit int, cursor string) (*FilePage, error) {
	query := url.Values{}
	if limit > 0 {
		query.Set("limit", fmt.Sprint(limit))
	}
	if cursor != "" {
		query.Set("cursor", cursor)
	}
	path := "/v1/files"
	if encoded := query.Encode(); encoded != "" {
		path += "?" + encoded
	}
	var page FilePage
	if err := c.request("GET", path, nil, &page); err != nil {
		return nil, err
	}
	return &page, nil
}

func (c *Client) GetFile(id string) (*File, error) {
	var out File
	if err := c.request("GET", "/v1/files/"+id, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) IssueUrlFile(id string, input map[string]any) (map[string]any, error) {
	out := map[string]any{}
	if err := c.request("POST", "/v1/files" + "/" + id + "/url", input, &out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) RemoveFile(id string) error {
	return c.request("DELETE", "/v1/files" + "/" + id, nil, nil)
}

func (c *Client) Search(q string, limit int64) (any, error) {
	query := url.Values{}
	query.Set("q", q)
	if limit > 0 {
		query.Set("limit", fmt.Sprint(limit))
	}
	path := "/v1/search"
	if encoded := query.Encode(); encoded != "" {
		path += "?" + encoded
	}
	var out any
	if err := c.request("GET", path, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) FileText(id string) (any, error) {
	path := "/v1/files/" + id + "/text"
	var out any
	if err := c.request("GET", path, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

