// Generated by janus for the `copal` contract v0.1.0 — do not edit.

export interface File {
  id: string
  path: string
  state: string
  contentType: string
  size?: number
  digest?: string
  metadata: unknown
  createdAt: string
}

export interface FilePage {
  items: File[]
  next_cursor?: string | null
}

export class Client {
  constructor(private baseUrl: string, private tenant: string) {}

  private async request<T>(method: string, path: string, body?: unknown): Promise<T> {
    const response = await fetch(`${this.baseUrl}${path}`, {
      method,
      headers: {
        'x-copal-tenant': this.tenant,
        ...(body === undefined ? {} : { 'content-type': 'application/json' }),
      },
      body: body === undefined ? undefined : JSON.stringify(body),
    })
    if (!response.ok) throw new Error(`${method} ${path}: ${response.status}`)
    if (response.status === 204) return undefined as T
    return (await response.json()) as T
  }

  listFiles(limit?: number, cursor?: string): Promise<FilePage> {
    const query = new URLSearchParams()
    if (limit !== undefined) query.set('limit', String(limit))
    if (cursor !== undefined) query.set('cursor', cursor)
    const suffix = query.size > 0 ? `?${query}` : ''
    return this.request('GET', `/v1/files${suffix}`)
  }

  getFile(id: string): Promise<File> {
    return this.request('GET', `/v1/files/${id}`)
  }

  issueUrlFile(id: string, input: Record<string, unknown>): Promise<Record<string, unknown>> {
    return this.request('POST', `/v1/files/${id}/url`, input)
  }

  removeFile(id: string): Promise<void> {
    return this.request('DELETE', `/v1/files/${id}`)
  }

}
