"""Generated by kayak for the `copal` contract v0.1.0. Do not edit."""

from __future__ import annotations

import json
import urllib.parse
import urllib.request
from dataclasses import dataclass, field
from typing import Any

@dataclass
class File:
  id: str
  path: str
  state: str
  content_type: str
  metadata: Any
  created_at: str
  size: int | None = None
  digest: str | None = None

@dataclass
class FilePage:
  items: list[File] = field(default_factory=list)
  next_cursor: str | None = None

class Client:
  def __init__(self, base_url: str, tenant: str) -> None:
    self.base_url = base_url.rstrip('/')
    self.tenant = tenant

  def _request(self, method: str, path: str, body: dict[str, Any] | None = None) -> Any:
    data = None if body is None else json.dumps(body).encode()
    headers = {'x-copal-tenant': self.tenant}
    if data is not None:
      headers['content-type'] = 'application/json'
    request = urllib.request.Request(
      f'{self.base_url}{path}', data=data, headers=headers, method=method,
    )
    with urllib.request.urlopen(request) as response:
      if response.status == 204:
        return None
      return json.loads(response.read())

  def list_files(self, limit: int | None = None, cursor: str | None = None) -> FilePage:
    query = {k: v for k, v in {'limit': limit, 'cursor': cursor}.items() if v is not None}
    suffix = f'?{urllib.parse.urlencode(query)}' if query else ''
    payload = self._request('GET', f'/v1/files{suffix}')
    return FilePage(
      items=[File(**{k: v for k, v in item.items() if k in File.__dataclass_fields__}) for item in payload.get('items', [])],
      next_cursor=payload.get('next_cursor'),
    )

  def get_file(self, id: str) -> File:
    item = self._request('GET', f'/v1/files/{id}')
    return File(**{k: v for k, v in item.items() if k in File.__dataclass_fields__})

  def issue_url_file(self, id: str, body: dict[str, Any] | None = None) -> Any:
    return self._request('POST', f'/v1/files/{id}/url', body or {})

  def remove_file(self, id: str) -> None:
    return self._request('DELETE', f'/v1/files/{id}')

  def search(self, q: str, limit: int | None = None) -> Any:
    query = {k: v for k, v in {'q': q, 'limit': limit}.items() if v is not None}
    suffix = f'?{urllib.parse.urlencode(query)}' if query else ''
    return self._request('GET', f'/v1/search{suffix}')

  def file_text(self, id: str) -> Any:
    return self._request('GET', f'/v1/files/{id}/text')

