//! Typed client generation: Rust, TypeScript, Python, Go.
//!
//! Each generator emits ONE self-contained source file: resource
//! types with the contract's renames and nullability, a client struct
//! carrying base URL and tenant, list/get per resource, and a method
//! per action. Dependency policy per language: Rust declares reqwest +
//! serde (stated in the file header); TypeScript uses `fetch`; Python
//! uses the standard library only; Go uses net/http only.
//!
//! This module is why the four SDKs stop being hand-maintained: one
//! contract, four clients, regenerated instead of ported.

use std::fmt::Write as _;

use surql::schema::{FieldDefinition, FieldType, TableDefinition};

use crate::ir::{ActionOutput, Contract, Query, TypeRef};
use crate::naming::{camel, pascal, singular, snake, type_name};
use crate::openapi::GenerateError;
use crate::validate::validate;

fn checked<'a>(
    contract: &'a Contract,
    schema: &'a [TableDefinition],
) -> Result<Vec<(&'a crate::ir::Resource, &'a TableDefinition)>, GenerateError> {
    let violations = validate(contract, schema);
    if !violations.is_empty() {
        return Err(GenerateError::Invalid(violations));
    }
    Ok(contract
        .resources
        .iter()
        .map(|resource| {
            let table = schema
                .iter()
                .find(|t| t.name == resource.table)
                .expect("validated: table exists");
            (resource, table)
        })
        .collect())
}

fn column<'a>(table: &'a TableDefinition, name: &str) -> &'a FieldDefinition {
    table
        .fields
        .iter()
        .find(|f| f.name == name)
        .expect("validated: column exists")
}

// ---------------------------------------------------------------- Rust

/// Generate the Rust client (reqwest + serde).
pub fn generate_client_rs(
    contract: &Contract,
    schema: &[TableDefinition],
) -> Result<String, GenerateError> {
    let resources = checked(contract, schema)?;
    let mut out = String::new();
    writeln!(
        out,
        "//! Generated by janus for the `{}` contract v{}. Do not edit.\n\
         //!\n\
         //! Dependencies: reqwest = {{ features = [\"json\"] }}, serde =\n\
         //! {{ features = [\"derive\"] }}, serde_json.\n",
        contract.name, contract.version,
    )
    .unwrap();
    out.push_str("use serde::Deserialize;\nuse serde_json::Value;\n\n");

    for (resource, table) in &resources {
        rust_struct(
            &mut out,
            &type_name(&resource.name),
            &resource.fields,
            table,
        );
        for sub in &resource.sub_resources {
            rust_struct(
                &mut out,
                &sub_type_name(resource, sub),
                &sub.fields,
                sub_table(schema, sub),
            );
        }
    }

    out.push_str(
        "#[derive(Debug, Clone)]\n\
         pub struct Client {\n\
         \x20   base_url: String,\n\
         \x20   tenant: String,\n\
         \x20   http: reqwest::Client,\n\
         }\n\n\
         pub type Error = Box<dyn std::error::Error + Send + Sync>;\n\n\
         impl Client {\n\
         \x20   pub fn new(base_url: impl Into<String>, tenant: impl Into<String>) -> Self {\n\
         \x20       Self {\n\
         \x20           base_url: base_url.into(),\n\
         \x20           tenant: tenant.into(),\n\
         \x20           http: reqwest::Client::new(),\n\
         \x20       }\n\
         \x20   }\n\n",
    );

    for (resource, _) in &resources {
        let name = type_name(&resource.name);
        let list_fn = format!("list_{}", snake(&resource.name));
        let get_fn = format!("get_{}", snake(&singular(&resource.name)));
        writeln!(
            out,
            "    pub async fn {list_fn}(&self, limit: Option<u32>, cursor: Option<&str>) \
             -> Result<{name}Page, Error> {{"
        )
        .unwrap();
        writeln!(
            out,
            "        let mut url = format!(\"{{}}/v1/{}\", self.base_url);",
            resource.name,
        )
        .unwrap();
        out.push_str(
            "        let mut query: Vec<(String, String)> = Vec::new();\n\
             \x20       if let Some(limit) = limit { query.push((\"limit\".into(), limit.to_string())); }\n\
             \x20       if let Some(cursor) = cursor { query.push((\"cursor\".into(), cursor.to_string())); }\n\
             \x20       if !query.is_empty() {\n\
             \x20           let joined: Vec<String> = query.iter().map(|(k, v)| format!(\"{k}={v}\")).collect();\n\
             \x20           url = format!(\"{url}?{}\", joined.join(\"&\"));\n\
             \x20       }\n",
        );
        writeln!(
            out,
            "        Ok(self.http.get(url).header(\"x-copal-tenant\", &self.tenant)\
             .send().await?.error_for_status()?.json().await?)"
        )
        .unwrap();
        out.push_str("    }\n\n");
        writeln!(
            out,
            "    pub async fn {get_fn}(&self, id: &str) -> Result<{name}, Error> {{"
        )
        .unwrap();
        writeln!(
            out,
            "        let url = format!(\"{{}}/v1/{}/{{id}}\", self.base_url);",
            resource.name,
        )
        .unwrap();
        writeln!(
            out,
            "        Ok(self.http.get(url).header(\"x-copal-tenant\", &self.tenant)\
             .send().await?.error_for_status()?.json().await?)"
        )
        .unwrap();
        out.push_str("    }\n\n");

        // One list method per sub-collection, reached through the
        // parent id.
        for sub in &resource.sub_resources {
            let sub_name = sub_type_name(resource, sub);
            writeln!(
                out,
                "    pub async fn {stem}(&self, id: &str, limit: Option<u32>, cursor: Option<&str>)                  -> Result<{sub_name}Page, Error> {{",
                stem = sub_method_stem(resource, sub),
            )
            .unwrap();
            writeln!(
                out,
                "        let mut url = format!(\"{{}}/v1/{}/{{id}}/{}\", self.base_url);",
                resource.name, sub.name,
            )
            .unwrap();
            out.push_str(
                "        let mut query: Vec<(String, String)> = Vec::new();
                         if let Some(limit) = limit { query.push((\"limit\".into(), limit.to_string())); }
                         if let Some(cursor) = cursor { query.push((\"cursor\".into(), cursor.to_string())); }
                         if !query.is_empty() {
                             let joined: Vec<String> = query.iter().map(|(k, v)| format!(\"{k}={v}\")).collect();
                             url = format!(\"{url}?{}\", joined.join(\"&\"));
                         }
                         Ok(self.http.get(url).header(\"x-copal-tenant\", &self.tenant)                 .send().await?.error_for_status()?.json().await?)
    }

",
            );
        }
        for action in &resource.actions {
            let method_fn = format!(
                "{}_{}",
                snake(&action.name),
                snake(&singular(&resource.name))
            );
            let mut parameters = vec!["&self".to_owned()];
            if action.takes_id() {
                parameters.push("id: &str".to_owned());
            }
            if !action.input.is_empty() {
                parameters.push("input: Value".to_owned());
            }
            let output = match action.output {
                ActionOutput::Resource => name.clone(),
                ActionOutput::Json => "Value".to_owned(),
                ActionOutput::None => "()".to_owned(),
            };
            writeln!(
                out,
                "    pub async fn {method_fn}({}) -> Result<{output}, Error> {{",
                parameters.join(", "),
            )
            .unwrap();
            // The literal `{id}` survives into the generated format!
            // string, where the method's `id` parameter interpolates.
            writeln!(
                out,
                "        let url = format!(\"{{}}/v1/{}{}\", self.base_url);",
                resource.name, action.path,
            )
            .unwrap();
            let verb = action.method.to_ascii_lowercase();
            let mut call =
                format!("self.http.{verb}(url).header(\"x-copal-tenant\", &self.tenant)");
            if !action.input.is_empty() {
                call.push_str(".json(&input)");
            }
            match action.output {
                ActionOutput::None => {
                    writeln!(
                        out,
                        "        {call}.send().await?.error_for_status()?;\n        Ok(())"
                    )
                    .unwrap();
                }
                _ => {
                    writeln!(
                        out,
                        "        Ok({call}.send().await?.error_for_status()?.json().await?)"
                    )
                    .unwrap();
                }
            }
            out.push_str("    }\n\n");
        }
    }
    // Queries: declared reads that are not listings. They reach REST
    // as GETs with their inputs in the query string, which is why they
    // carry no body and return open JSON.
    for query in &contract.queries {
        let mut parameters = vec!["&self".to_owned()];
        if query_takes_id(query) {
            parameters.push("id: &str".to_owned());
        }
        for field in query_params(query) {
            let kind = query_kind(field.kind, "rs");
            parameters.push(if field.required {
                format!("{}: {kind}", snake(&field.name))
            } else {
                format!("{}: Option<{kind}>", snake(&field.name))
            });
        }
        writeln!(
            out,
            "    pub async fn {}({}) -> Result<Value, Error> {{",
            snake(&query.name),
            parameters.join(", "),
        )
        .unwrap();
        writeln!(
            out,
            "        let url = format!(\"{{}}{}\", self.base_url);",
            query.path,
        )
        .unwrap();
        // `mut` only when something reassigns it, so a query with no
        // parameters does not generate a warning in the client.
        let binding = if query_params(query).is_empty() {
            "let request"
        } else {
            "let mut request"
        };
        writeln!(
            out,
            "        {binding} = self.http.get(url)\n\
             \x20           .header(\"x-copal-tenant\", &self.tenant);",
        )
        .unwrap();
        for field in query_params(query) {
            let name = &field.name;
            let binding = snake(name);
            if field.required {
                writeln!(
                    out,
                    "        request = request.query(&[(\"{name}\", {binding})]);",
                )
                .unwrap();
            } else {
                writeln!(
                    out,
                    "        if let Some(value) = {binding} {{\n\
                     \x20           request = request.query(&[(\"{name}\", value)]);\n\
                     \x20       }}",
                )
                .unwrap();
            }
        }
        out.push_str(
            "        Ok(request.send().await?.error_for_status()?.json().await?)\n    }\n\n",
        );
    }
    out.push_str("}\n");
    Ok(out)
}

// ---------------------------------------------------------- TypeScript

/// Whether a query reads one instance, which is the only path
/// parameter the IR spells (`{id}`, as actions use).
fn query_takes_id(query: &Query) -> bool {
    query.path.contains("{id}")
}

/// The inputs that travel as query-string values: everything except
/// the one the path already carries.
fn query_params(query: &Query) -> Vec<&crate::ir::ActionField> {
    let mut params: Vec<&crate::ir::ActionField> = query
        .input
        .iter()
        .filter(|field| !(query_takes_id(query) && field.name == "id"))
        .collect();
    // TypeScript and Python both refuse a required parameter after an
    // optional one, so the required ones lead. A stable sort keeps the
    // contract's order within each group, which keeps goldens stable.
    params.sort_by_key(|field| !field.required);
    params
}

/// A query answers with whatever its resolver decided, and the IR
/// declares no shape for it, so every generated method returns the
/// language's open JSON type. Inventing a struct here would be
/// inventing a promise the contract does not make.
fn query_kind(kind: TypeRef, language: &str) -> &'static str {
    match (language, kind) {
        ("rs", TypeRef::Int) => "i64",
        ("rs", TypeRef::Bool) => "bool",
        ("rs", TypeRef::Json) => "Value",
        ("rs", _) => "&str",
        ("ts", TypeRef::Int) => "number",
        ("ts", TypeRef::Bool) => "boolean",
        ("ts", TypeRef::Json) => "unknown",
        ("ts", _) => "string",
        ("py", TypeRef::Int) => "int",
        ("py", TypeRef::Bool) => "bool",
        ("py", TypeRef::Json) => "Any",
        ("py", _) => "str",
        ("go", TypeRef::Int) => "int64",
        ("go", TypeRef::Bool) => "bool",
        ("go", TypeRef::Json) => "any",
        _ => "string",
    }
}

/// Generate the TypeScript client (fetch, zero dependencies).
pub fn generate_client_ts(
    contract: &Contract,
    schema: &[TableDefinition],
) -> Result<String, GenerateError> {
    let resources = checked(contract, schema)?;
    let mut out = String::new();
    writeln!(
        out,
        "// Generated by janus for the `{}` contract v{}. Do not edit.\n",
        contract.name, contract.version,
    )
    .unwrap();

    for (resource, table) in &resources {
        ts_interface(
            &mut out,
            &type_name(&resource.name),
            &resource.fields,
            table,
        );
        for sub in &resource.sub_resources {
            ts_interface(
                &mut out,
                &sub_type_name(resource, sub),
                &sub.fields,
                sub_table(schema, sub),
            );
        }
    }

    out.push_str(
        "export class Client {\n\
         \x20 constructor(private baseUrl: string, private tenant: string) {}\n\n\
         \x20 private async request<T>(method: string, path: string, body?: unknown): Promise<T> {\n\
         \x20   const response = await fetch(`${this.baseUrl}${path}`, {\n\
         \x20     method,\n\
         \x20     headers: {\n\
         \x20       'x-copal-tenant': this.tenant,\n\
         \x20       ...(body === undefined ? {} : { 'content-type': 'application/json' }),\n\
         \x20     },\n\
         \x20     body: body === undefined ? undefined : JSON.stringify(body),\n\
         \x20   })\n\
         \x20   if (!response.ok) throw new Error(`${method} ${path}: ${response.status}`)\n\
         \x20   if (response.status === 204) return undefined as T\n\
         \x20   return (await response.json()) as T\n\
         \x20 }\n\n",
    );

    for (resource, _) in &resources {
        let name = type_name(&resource.name);
        let list_fn = camel(&format!("list_{}", snake(&resource.name)));
        let get_fn = camel(&format!("get_{}", snake(&singular(&resource.name))));
        writeln!(
            out,
            "  {list_fn}(limit?: number, cursor?: string): Promise<{name}Page> {{"
        )
        .unwrap();
        writeln!(
            out,
            "    const query = new URLSearchParams()\n\
             \x20   if (limit !== undefined) query.set('limit', String(limit))\n\
             \x20   if (cursor !== undefined) query.set('cursor', cursor)\n\
             \x20   const suffix = query.size > 0 ? `?${{query}}` : ''\n\
             \x20   return this.request('GET', `/v1/{}${{suffix}}`)",
            resource.name,
        )
        .unwrap();
        out.push_str("  }\n\n");
        writeln!(out, "  {get_fn}(id: string): Promise<{name}> {{").unwrap();
        writeln!(
            out,
            "    return this.request('GET', `/v1/{}/${{id}}`)",
            resource.name,
        )
        .unwrap();
        out.push_str("  }\n\n");

        for sub in &resource.sub_resources {
            let sub_name = sub_type_name(resource, sub);
            writeln!(
                out,
                "  {stem}(id: string, limit?: number, cursor?: string): Promise<{sub_name}Page> {{",
                stem = camel(&sub_method_stem(resource, sub)),
            )
            .unwrap();
            writeln!(
                out,
                "    const query = new URLSearchParams()
                     if (limit !== undefined) query.set('limit', String(limit))
                     if (cursor !== undefined) query.set('cursor', cursor)
                     const suffix = query.size > 0 ? `?${{query}}` : ''
                     return this.request('GET', `/v1/{}/${{id}}/{}${{suffix}}`)",
                resource.name, sub.name,
            )
            .unwrap();
            out.push_str(
                "  }

",
            );
        }
        for action in &resource.actions {
            let method_fn = camel(&format!(
                "{}_{}",
                snake(&action.name),
                snake(&singular(&resource.name)),
            ));
            let mut parameters = Vec::new();
            if action.takes_id() {
                parameters.push("id: string".to_owned());
            }
            if !action.input.is_empty() {
                parameters.push("input: Record<string, unknown>".to_owned());
            }
            let output = match action.output {
                ActionOutput::Resource => name.clone(),
                ActionOutput::Json => "Record<string, unknown>".to_owned(),
                ActionOutput::None => "void".to_owned(),
            };
            let path = action.path.replace("{id}", "${id}");
            let body_argument = if action.input.is_empty() {
                ""
            } else {
                ", input"
            };
            writeln!(
                out,
                "  {method_fn}({}): Promise<{output}> {{",
                parameters.join(", "),
            )
            .unwrap();
            writeln!(
                out,
                "    return this.request('{}', `/v1/{}{path}`{body_argument})",
                action.method, resource.name,
            )
            .unwrap();
            out.push_str("  }\n\n");
        }
    }
    // Queries reach REST as GETs carrying their inputs in the query
    // string. They declare no output shape, so the method answers with
    // open JSON.
    for query in &contract.queries {
        let mut parameters = Vec::new();
        if query_takes_id(query) {
            parameters.push("id: string".to_owned());
        }
        for field in query_params(query) {
            let kind = query_kind(field.kind, "ts");
            parameters.push(if field.required {
                format!("{}: {kind}", camel(&field.name))
            } else {
                format!("{}?: {kind}", camel(&field.name))
            });
        }
        writeln!(
            out,
            "  {}({}): Promise<unknown> {{",
            camel(&query.name),
            parameters.join(", "),
        )
        .unwrap();
        let path = query.path.replace("{id}", "${id}");
        if query_params(query).is_empty() {
            // Nothing to encode, so nothing is built.
            writeln!(out, "    return this.request('GET', `{path}`)").unwrap();
        } else {
            out.push_str("    const query = new URLSearchParams()\n");
            for field in query_params(query) {
                let name = &field.name;
                let binding = camel(name);
                if field.required {
                    writeln!(out, "    query.set('{name}', String({binding}))").unwrap();
                } else {
                    writeln!(
                        out,
                        "    if ({binding} !== undefined) query.set('{name}', String({binding}))",
                    )
                    .unwrap();
                }
            }
            out.push_str("    const suffix = query.size > 0 ? `?${query}` : ''\n");
            writeln!(out, "    return this.request('GET', `{path}${{suffix}}`)").unwrap();
        }
        out.push_str("  }\n\n");
    }
    out.push_str("}\n");
    Ok(out)
}

// -------------------------------------------------------------- Python

/// Generate the Python client (standard library only).
pub fn generate_client_py(
    contract: &Contract,
    schema: &[TableDefinition],
) -> Result<String, GenerateError> {
    let resources = checked(contract, schema)?;
    let mut out = String::new();
    writeln!(
        out,
        "\"\"\"Generated by janus for the `{}` contract v{}. Do not edit.\"\"\"\n",
        contract.name, contract.version,
    )
    .unwrap();
    out.push_str(
        "from __future__ import annotations\n\n\
         import json\n\
         import urllib.parse\n\
         import urllib.request\n\
         from dataclasses import dataclass, field\n\
         from typing import Any\n\n",
    );

    for (resource, table) in &resources {
        py_dataclass(
            &mut out,
            &type_name(&resource.name),
            &resource.fields,
            table,
        );
        for sub in &resource.sub_resources {
            py_dataclass(
                &mut out,
                &sub_type_name(resource, sub),
                &sub.fields,
                sub_table(schema, sub),
            );
        }
    }

    out.push_str(
        "class Client:\n\
         \x20 def __init__(self, base_url: str, tenant: str) -> None:\n\
         \x20   self.base_url = base_url.rstrip('/')\n\
         \x20   self.tenant = tenant\n\n\
         \x20 def _request(self, method: str, path: str, body: dict[str, Any] | None = None) -> Any:\n\
         \x20   data = None if body is None else json.dumps(body).encode()\n\
         \x20   headers = {'x-copal-tenant': self.tenant}\n\
         \x20   if data is not None:\n\
         \x20     headers['content-type'] = 'application/json'\n\
         \x20   request = urllib.request.Request(\n\
         \x20     f'{self.base_url}{path}', data=data, headers=headers, method=method,\n\
         \x20   )\n\
         \x20   with urllib.request.urlopen(request) as response:\n\
         \x20     if response.status == 204:\n\
         \x20       return None\n\
         \x20     return json.loads(response.read())\n\n",
    );

    for (resource, _) in &resources {
        let name = type_name(&resource.name);
        let fields_from = format!(
            "{name}(**{{k: v for k, v in item.items() if k in {name}.__dataclass_fields__}})"
        );
        writeln!(
            out,
            "  def list_{plural}(self, limit: int | None = None, cursor: str | None = None) -> {name}Page:",
            plural = snake(&resource.name),
        )
        .unwrap();
        writeln!(
            out,
            "    query = {{k: v for k, v in {{'limit': limit, 'cursor': cursor}}.items() if v is not None}}\n\
             \x20   suffix = f'?{{urllib.parse.urlencode(query)}}' if query else ''\n\
             \x20   payload = self._request('GET', f'/v1/{plural}{{suffix}}')\n\
             \x20   return {name}Page(\n\
             \x20     items=[{fields_from} for item in payload.get('items', [])],\n\
             \x20     next_cursor=payload.get('next_cursor'),\n\
             \x20   )\n",
            plural = resource.name,
        )
        .unwrap();
        writeln!(
            out,
            "  def get_{single}(self, id: str) -> {name}:\n\
             \x20   item = self._request('GET', f'/v1/{plural}/{{id}}')\n\
             \x20   return {fields_from}\n",
            single = snake(&singular(&resource.name)),
            plural = resource.name,
        )
        .unwrap();

        for sub in &resource.sub_resources {
            let sub_name = sub_type_name(resource, sub);
            let sub_from = format!(
                "{sub_name}(**{{k: v for k, v in item.items() if k in {sub_name}.__dataclass_fields__}})"
            );
            writeln!(
                out,
                "  def {stem}(self, id: str, limit: int | None = None, cursor: str | None = None) -> {sub_name}Page:",
                stem = snake(&sub_method_stem(resource, sub)),
            )
            .unwrap();
            let body = [
                "    query = {k: v for k, v in {'limit': limit, 'cursor': cursor}.items() if v is not None}"
                    .to_owned(),
                "    suffix = f'?{urllib.parse.urlencode(query)}' if query else ''".to_owned(),
                format!(
                    "    payload = self._request('GET', f'/v1/{parent}/{{id}}/{child}{{suffix}}')",
                    parent = resource.name,
                    child = sub.name,
                ),
                format!("    return {sub_name}Page("),
                format!("      items=[{sub_from} for item in payload.get('items', [])],"),
                "      next_cursor=payload.get('next_cursor'),".to_owned(),
                "    )".to_owned(),
            ];
            writeln!(out, "{}", body.join("\n")).unwrap();
        }
        for action in &resource.actions {
            let method_fn = format!(
                "{}_{}",
                snake(&action.name),
                snake(&singular(&resource.name)),
            );
            let mut parameters = vec!["self".to_owned()];
            if action.takes_id() {
                parameters.push("id: str".to_owned());
            }
            if !action.input.is_empty() {
                parameters.push("body: dict[str, Any] | None = None".to_owned());
            }
            let returns = match action.output {
                ActionOutput::Resource => name.clone(),
                ActionOutput::Json => "Any".to_owned(),
                ActionOutput::None => "None".to_owned(),
            };
            // The literal `{id}` survives into the generated f-string,
            // where the method's `id` parameter interpolates.
            let path = &action.path;
            let body_argument = if action.input.is_empty() {
                String::new()
            } else {
                ", body or {}".to_owned()
            };
            writeln!(
                out,
                "  def {method_fn}({params}) -> {returns}:",
                params = parameters.join(", "),
            )
            .unwrap();
            match action.output {
                ActionOutput::Resource => {
                    writeln!(
                        out,
                        "    item = self._request('{method}', f'/v1/{plural}{path}'{body_argument})\n\
                         \x20   return {fields_from}\n",
                        method = action.method,
                        plural = resource.name,
                    )
                    .unwrap();
                }
                _ => {
                    writeln!(
                        out,
                        "    return self._request('{method}', f'/v1/{plural}{path}'{body_argument})\n",
                        method = action.method,
                        plural = resource.name,
                    )
                    .unwrap();
                }
            }
        }
    }
    for query in &contract.queries {
        let mut parameters = vec!["self".to_owned()];
        if query_takes_id(query) {
            parameters.push("id: str".to_owned());
        }
        for field in query_params(query) {
            let kind = query_kind(field.kind, "py");
            parameters.push(if field.required {
                format!("{}: {kind}", snake(&field.name))
            } else {
                format!("{}: {kind} | None = None", snake(&field.name))
            });
        }
        writeln!(
            out,
            "  def {}({}) -> Any:",
            snake(&query.name),
            parameters.join(", "),
        )
        .unwrap();
        if query_params(query).is_empty() {
            writeln!(out, "    return self._request('GET', f'{}')\n", query.path).unwrap();
        } else {
            let pairs: Vec<String> = query_params(query)
                .iter()
                .map(|field| format!("'{}': {}", field.name, snake(&field.name)))
                .collect();
            writeln!(
                out,
                "    query = {{k: v for k, v in {{{}}}.items() if v is not None}}",
                pairs.join(", "),
            )
            .unwrap();
            out.push_str("    suffix = f'?{urllib.parse.urlencode(query)}' if query else ''\n");
            writeln!(
                out,
                "    return self._request('GET', f'{}{{suffix}}')\n",
                query.path,
            )
            .unwrap();
        }
    }
    Ok(out)
}

// ------------------------------------------------------------------ Go

/// Generate the Go client (net/http only).
pub fn generate_client_go(
    contract: &Contract,
    schema: &[TableDefinition],
) -> Result<String, GenerateError> {
    let resources = checked(contract, schema)?;
    let mut out = String::new();
    writeln!(
        out,
        "// Code generated by janus for the `{}` contract v{}; DO NOT EDIT.\n",
        contract.name, contract.version,
    )
    .unwrap();
    writeln!(out, "package {}\n", snake(&contract.name)).unwrap();
    out.push_str(
        "import (\n\
         \t\"bytes\"\n\
         \t\"encoding/json\"\n\
         \t\"fmt\"\n\
         \t\"net/http\"\n\
         \t\"net/url\"\n\
         )\n\n",
    );

    for (resource, table) in &resources {
        go_struct(
            &mut out,
            &type_name(&resource.name),
            &resource.fields,
            table,
        );
        for sub in &resource.sub_resources {
            go_struct(
                &mut out,
                &sub_type_name(resource, sub),
                &sub.fields,
                sub_table(schema, sub),
            );
        }
    }

    out.push_str(
        "type Client struct {\n\
         \tBaseURL string\n\
         \tTenant  string\n\
         \tHTTP    *http.Client\n\
         }\n\n\
         func NewClient(baseURL, tenant string) *Client {\n\
         \treturn &Client{BaseURL: baseURL, Tenant: tenant, HTTP: http.DefaultClient}\n\
         }\n\n\
         func (c *Client) request(method, path string, body any, out any) error {\n\
         \tvar payload *bytes.Buffer\n\
         \tif body != nil {\n\
         \t\tencoded, err := json.Marshal(body)\n\
         \t\tif err != nil {\n\
         \t\t\treturn err\n\
         \t\t}\n\
         \t\tpayload = bytes.NewBuffer(encoded)\n\
         \t} else {\n\
         \t\tpayload = bytes.NewBuffer(nil)\n\
         \t}\n\
         \trequest, err := http.NewRequest(method, c.BaseURL+path, payload)\n\
         \tif err != nil {\n\
         \t\treturn err\n\
         \t}\n\
         \trequest.Header.Set(\"x-copal-tenant\", c.Tenant)\n\
         \tif body != nil {\n\
         \t\trequest.Header.Set(\"content-type\", \"application/json\")\n\
         \t}\n\
         \tresponse, err := c.HTTP.Do(request)\n\
         \tif err != nil {\n\
         \t\treturn err\n\
         \t}\n\
         \tdefer response.Body.Close()\n\
         \tif response.StatusCode >= 400 {\n\
         \t\treturn fmt.Errorf(\"%s %s: %d\", method, path, response.StatusCode)\n\
         \t}\n\
         \tif out == nil || response.StatusCode == 204 {\n\
         \t\treturn nil\n\
         \t}\n\
         \treturn json.NewDecoder(response.Body).Decode(out)\n\
         }\n\n",
    );

    for (resource, _) in &resources {
        let name = type_name(&resource.name);
        writeln!(
            out,
            "func (c *Client) List{plural}(limit int, cursor string) (*{name}Page, error) {{",
            plural = pascal(&snake(&resource.name)),
        )
        .unwrap();
        writeln!(
            out,
            "\tquery := url.Values{{}}\n\
             \tif limit > 0 {{\n\
             \t\tquery.Set(\"limit\", fmt.Sprint(limit))\n\
             \t}}\n\
             \tif cursor != \"\" {{\n\
             \t\tquery.Set(\"cursor\", cursor)\n\
             \t}}\n\
             \tpath := \"/v1/{plural}\"\n\
             \tif encoded := query.Encode(); encoded != \"\" {{\n\
             \t\tpath += \"?\" + encoded\n\
             \t}}\n\
             \tvar page {name}Page\n\
             \tif err := c.request(\"GET\", path, nil, &page); err != nil {{\n\
             \t\treturn nil, err\n\
             \t}}\n\
             \treturn &page, nil\n}}\n",
            plural = resource.name,
        )
        .unwrap();
        writeln!(
            out,
            "func (c *Client) Get{single}(id string) (*{name}, error) {{\n\
             \tvar out {name}\n\
             \tif err := c.request(\"GET\", \"/v1/{plural}/\"+id, nil, &out); err != nil {{\n\
             \t\treturn nil, err\n\
             \t}}\n\
             \treturn &out, nil\n}}\n",
            single = pascal(&singular(&resource.name)),
            plural = resource.name,
        )
        .unwrap();

        for sub in &resource.sub_resources {
            let sub_name = sub_type_name(resource, sub);
            writeln!(
                out,
                "func (c *Client) {stem}(id string, limit int, cursor string) (*{sub_name}Page, error) {{",
                stem = pascal(&sub_method_stem(resource, sub)),
            )
            .unwrap();
            writeln!(
                out,
                "	query := url.Values{{}}
                 	if limit > 0 {{
                 		query.Set(\"limit\", fmt.Sprint(limit))
                 	}}
                 	if cursor != \"\" {{
                 		query.Set(\"cursor\", cursor)
                 	}}
                 	path := \"/v1/{parent}/\" + id + \"/{child}\"
                 	if encoded := query.Encode(); encoded != \"\" {{
                 		path += \"?\" + encoded
                 	}}
                 	var page {sub_name}Page
                 	if err := c.request(\"GET\", path, nil, &page); err != nil {{
                 		return nil, err
                 	}}
                 	return &page, nil
}}
",
                parent = resource.name,
                child = sub.name,
            )
            .unwrap();
        }
        for action in &resource.actions {
            let method_name = format!(
                "{}{}",
                pascal(&snake(&action.name)),
                pascal(&singular(&resource.name)),
            );
            let mut parameters = Vec::new();
            if action.takes_id() {
                parameters.push("id string".to_owned());
            }
            if !action.input.is_empty() {
                parameters.push("input map[string]any".to_owned());
            }
            let path_expression = if action.takes_id() {
                format!("\"/v1/{}\" + {}", resource.name, go_path_expr(&action.path),)
            } else {
                format!("\"/v1/{}{}\"", resource.name, action.path)
            };
            let body_expression = if action.input.is_empty() {
                "nil"
            } else {
                "input"
            };
            match action.output {
                ActionOutput::Resource => {
                    writeln!(
                        out,
                        "func (c *Client) {method_name}({params}) (*{name}, error) {{\n\
                         \tvar out {name}\n\
                         \tif err := c.request(\"{method}\", {path_expression}, {body_expression}, &out); err != nil {{\n\
                         \t\treturn nil, err\n\
                         \t}}\n\
                         \treturn &out, nil\n}}\n",
                        params = parameters.join(", "),
                        method = action.method,
                    )
                    .unwrap();
                }
                ActionOutput::Json => {
                    writeln!(
                        out,
                        "func (c *Client) {method_name}({params}) (map[string]any, error) {{\n\
                         \tout := map[string]any{{}}\n\
                         \tif err := c.request(\"{method}\", {path_expression}, {body_expression}, &out); err != nil {{\n\
                         \t\treturn nil, err\n\
                         \t}}\n\
                         \treturn out, nil\n}}\n",
                        params = parameters.join(", "),
                        method = action.method,
                    )
                    .unwrap();
                }
                ActionOutput::None => {
                    writeln!(
                        out,
                        "func (c *Client) {method_name}({params}) error {{\n\
                         \treturn c.request(\"{method}\", {path_expression}, {body_expression}, nil)\n}}\n",
                        params = parameters.join(", "),
                        method = action.method,
                    )
                    .unwrap();
                }
            }
        }
    }
    for query in &contract.queries {
        let mut parameters = Vec::new();
        if query_takes_id(query) {
            parameters.push("id string".to_owned());
        }
        for field in query_params(query) {
            parameters.push(format!(
                "{} {}",
                camel(&field.name),
                query_kind(field.kind, "go"),
            ));
        }
        writeln!(
            out,
            "func (c *Client) {}({}) (any, error) {{",
            pascal(&snake(&query.name)),
            parameters.join(", "),
        )
        .unwrap();
        if !query_params(query).is_empty() {
            out.push_str("\tquery := url.Values{}\n");
        }
        for field in query_params(query) {
            let name = &field.name;
            let binding = camel(name);
            // Go has no optional parameter, so an omitted value arrives
            // as the zero value and the zero value is what gets
            // skipped. The generated listings already read this way.
            let guard = match field.kind {
                TypeRef::Int => Some(format!("{binding} > 0")),
                TypeRef::String => Some(format!("{binding} != \"\"")),
                _ => None,
            };
            let setter = match field.kind {
                TypeRef::String => format!("query.Set(\"{name}\", {binding})"),
                _ => format!("query.Set(\"{name}\", fmt.Sprint({binding}))"),
            };
            match (field.required, guard) {
                (false, Some(condition)) => {
                    writeln!(out, "\tif {condition} {{\n\t\t{setter}\n\t}}").unwrap();
                }
                _ => writeln!(out, "\t{setter}").unwrap(),
            }
        }
        let path_expression = if query_takes_id(query) {
            go_path_expr(&query.path)
        } else {
            format!("\"{}\"", query.path)
        };
        writeln!(out, "\tpath := {path_expression}").unwrap();
        if !query_params(query).is_empty() {
            out.push_str(
                "\tif encoded := query.Encode(); encoded != \"\" {\n\
                 \t\tpath += \"?\" + encoded\n\t}\n",
            );
        }
        out.push_str(
            "\tvar out any\n\
             \tif err := c.request(\"GET\", path, nil, &out); err != nil {\n\
             \t\treturn nil, err\n\t}\n\
             \treturn out, nil\n}\n\n",
        );
    }
    Ok(out)
}

/// Render a Go expression for an action path with `{id}` spliced in.
fn go_path_expr(path: &str) -> String {
    let (before, after) = path.split_once("{id}").expect("takes_id checked");
    let mut expression = String::new();
    if !before.is_empty() {
        expression.push_str(&format!("\"{before}\" + "));
    }
    expression.push_str("id");
    if !after.is_empty() {
        expression.push_str(&format!(" + \"{after}\""));
    }
    expression
}

/// The schema table a sub-resource reads, resolved after validation
/// has already proved it exists.
fn sub_table<'a>(
    schema: &'a [TableDefinition],
    sub: &crate::ir::SubResource,
) -> &'a TableDefinition {
    schema
        .iter()
        .find(|t| t.name == sub.table)
        .expect("validated: table exists")
}

/// The generated type name for a sub-resource, composed with the
/// parent so two parents may each carry a `versions` collection.
fn sub_type_name(parent: &crate::ir::Resource, sub: &crate::ir::SubResource) -> String {
    format!("{}{}", type_name(&parent.name), type_name(&sub.name))
}

/// The method stem that reaches a sub-collection: `versions` under
/// `files` becomes `list_versions_files`, matching the OpenAPI
/// operationId.
fn sub_method_stem(parent: &crate::ir::Resource, sub: &crate::ir::SubResource) -> String {
    format!("list_{}_{}", snake(&sub.name), snake(&parent.name))
}

/// One Rust struct plus its page envelope.
fn rust_struct(
    out: &mut String,
    name: &str,
    fields: &[crate::ir::FieldExposure],
    table: &TableDefinition,
) {
    writeln!(out, "#[derive(Debug, Clone, Deserialize)]").unwrap();
    writeln!(out, "pub struct {name} {{").unwrap();
    writeln!(out, "    pub id: String,").unwrap();
    for exposure in fields {
        let field = column(table, &exposure.column);
        let base = match field.field_type {
            FieldType::Int => "i64",
            FieldType::Float | FieldType::Decimal | FieldType::Number => "f64",
            FieldType::Bool => "bool",
            FieldType::Object | FieldType::Array | FieldType::Geometry | FieldType::Any => "Value",
            _ => "String",
        };
        let optional = field.nullable || exposure.guard.is_some();
        let ty = if optional {
            format!("Option<{base}>")
        } else {
            base.to_owned()
        };
        let api = exposure.api_name();
        if optional {
            writeln!(out, "    #[serde(default)]").unwrap();
        }
        writeln!(out, "    pub {}: {ty},", snake(api)).unwrap();
    }
    writeln!(out, "}}\n").unwrap();
    writeln!(out, "#[derive(Debug, Clone, Deserialize)]").unwrap();
    writeln!(out, "pub struct {name}Page {{").unwrap();
    writeln!(out, "    pub items: Vec<{name}>,").unwrap();
    writeln!(out, "    #[serde(default)]").unwrap();
    writeln!(out, "    pub next_cursor: Option<String>,").unwrap();
    writeln!(out, "}}\n").unwrap();
}

/// One TypeScript interface plus its page envelope.
fn ts_interface(
    out: &mut String,
    name: &str,
    fields: &[crate::ir::FieldExposure],
    table: &TableDefinition,
) {
    writeln!(out, "export interface {name} {{").unwrap();
    writeln!(out, "  id: string").unwrap();
    for exposure in fields {
        let field = column(table, &exposure.column);
        let base = match field.field_type {
            FieldType::Int | FieldType::Float | FieldType::Decimal | FieldType::Number => "number",
            FieldType::Bool => "boolean",
            FieldType::Object | FieldType::Array | FieldType::Geometry | FieldType::Any => {
                "unknown"
            }
            _ => "string",
        };
        let optional = if field.nullable || exposure.guard.is_some() {
            "?"
        } else {
            ""
        };
        writeln!(out, "  {}{optional}: {base}", camel(exposure.api_name())).unwrap();
    }
    writeln!(out, "}}\n").unwrap();
    writeln!(out, "export interface {name}Page {{").unwrap();
    writeln!(out, "  items: {name}[]").unwrap();
    writeln!(out, "  next_cursor?: string | null").unwrap();
    writeln!(out, "}}\n").unwrap();
}

/// One Python dataclass plus its page envelope. Required attributes
/// precede defaulted ones, which dataclass rules demand.
fn py_dataclass(
    out: &mut String,
    name: &str,
    fields: &[crate::ir::FieldExposure],
    table: &TableDefinition,
) {
    writeln!(out, "@dataclass\nclass {name}:").unwrap();
    writeln!(out, "  id: str").unwrap();
    let mut required_lines = Vec::new();
    let mut optional_lines = Vec::new();
    for exposure in fields {
        let schema_field = column(table, &exposure.column);
        let base = match schema_field.field_type {
            FieldType::Int => "int",
            FieldType::Float | FieldType::Decimal | FieldType::Number => "float",
            FieldType::Bool => "bool",
            FieldType::Object | FieldType::Array | FieldType::Geometry | FieldType::Any => "Any",
            _ => "str",
        };
        let attribute = snake(exposure.api_name());
        if schema_field.nullable || exposure.guard.is_some() {
            optional_lines.push(format!("  {attribute}: {base} | None = None"));
        } else {
            required_lines.push(format!("  {attribute}: {base}"));
        }
    }
    for line in required_lines.into_iter().chain(optional_lines) {
        writeln!(out, "{line}").unwrap();
    }
    writeln!(out).unwrap();
    writeln!(out, "@dataclass\nclass {name}Page:").unwrap();
    writeln!(out, "  items: list[{name}] = field(default_factory=list)").unwrap();
    writeln!(out, "  next_cursor: str | None = None\n").unwrap();
}

/// One Go struct plus its page envelope.
fn go_struct(
    out: &mut String,
    name: &str,
    fields: &[crate::ir::FieldExposure],
    table: &TableDefinition,
) {
    writeln!(out, "type {name} struct {{").unwrap();
    writeln!(out, "\tID string `json:\"id\"`").unwrap();
    for exposure in fields {
        let field = column(table, &exposure.column);
        let base = match field.field_type {
            FieldType::Int => "int64",
            FieldType::Float | FieldType::Decimal | FieldType::Number => "float64",
            FieldType::Bool => "bool",
            FieldType::Object | FieldType::Array | FieldType::Geometry | FieldType::Any => "any",
            _ => "string",
        };
        let go_type = if (field.nullable || exposure.guard.is_some()) && base != "any" {
            format!("*{base}")
        } else {
            base.to_owned()
        };
        let api = exposure.api_name();
        writeln!(out, "\t{} {go_type} `json:\"{api}\"`", pascal(&snake(api))).unwrap();
    }
    writeln!(out, "}}\n").unwrap();
    writeln!(out, "type {name}Page struct {{").unwrap();
    writeln!(out, "\tItems []{name} `json:\"items\"`").unwrap();
    writeln!(out, "\tNextCursor *string `json:\"next_cursor\"`").unwrap();
    writeln!(out, "}}\n").unwrap();
}
